---
- name: Install libfontconfig package
  apt:
    name: libfontconfig
    state: present
  sudo: yes

- name: Install CasperJS via Node.js package manager(npm)
  npm: name='casperjs' global=yes
  sudo: yes
