---

- name: Download Node.js package
  shell: "curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -"
  register: nodejs_downloaded
  sudo: yes

- name: Install Node.js
  when: nodejs_downloaded
  apt:
    name: 'nodejs'
    state: present
  register: nodejs_installed
  sudo: yes

- name: Install build tools
  when: nodejs_downloaded
  apt:
    name: 'build-essential'
    state: present
  sudo: yes
