---

- name: Make sure the packages are installed (Debian)
  apt:
    pkg: "{{item}}"
    state: present
  with_items: python_packages
  when: ansible_os_family == "Debian"

- name: Install pip
  apt: name='python-pip' state='present'
  sudo: yes
